// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uvYUvHkrq5oTFJ-h6Qbyi26glK6zPLE',
    appId: '1:1077671680762:web:225ad05acd7b0491bf8743',
    messagingSenderId: '1077671680762',
    projectId: 'college-canteen-54a24',
    authDomain: 'college-canteen-54a24.firebaseapp.com',
    storageBucket: 'college-canteen-54a24.firebasestorage.app',
    measurementId: 'G-DNVG7HC8XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALDZPVavd2IhYm7Ro0GACYs0mUnMWwnBo',
    appId: '1:1077671680762:android:1e0be1556a7cc96dbf8743',
    messagingSenderId: '1077671680762',
    projectId: 'college-canteen-54a24',
    storageBucket: 'college-canteen-54a24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMk61Cs9FwxoTNW96W61x_TDoQy1aNiJU',
    appId: '1:1077671680762:ios:d8832c897e1c8869bf8743',
    messagingSenderId: '1077671680762',
    projectId: 'college-canteen-54a24',
    storageBucket: 'college-canteen-54a24.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMk61Cs9FwxoTNW96W61x_TDoQy1aNiJU',
    appId: '1:1077671680762:ios:d8832c897e1c8869bf8743',
    messagingSenderId: '1077671680762',
    projectId: 'college-canteen-54a24',
    storageBucket: 'college-canteen-54a24.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2uvYUvHkrq5oTFJ-h6Qbyi26glK6zPLE',
    appId: '1:1077671680762:web:8cc298821e0f06f7bf8743',
    messagingSenderId: '1077671680762',
    projectId: 'college-canteen-54a24',
    authDomain: 'college-canteen-54a24.firebaseapp.com',
    storageBucket: 'college-canteen-54a24.firebasestorage.app',
    measurementId: 'G-GPFCKZHDC0',
  );
}
